### ISSUE TITLE
Rebalance Document does not have csv icon

### ISSUE THREAD

**Issue by VinceMazzurco** [fcfort/betterment-csv-chrome#37]
Hi, I use Betterment but as you point out, the brokerage firm is good and low expenses. I was looking to import the data into quicken and use to analyze the data since I can keep track of all of the dividends and transactions they perform. Lately, a new document was created called Rebalance, not sure why your chrome extension does not automatically pick up the pdf document and do you have plans in updating to convert this new document called Rebalance? Thanks Vince

**Comment by fcfort** [comment]
Hi Vince,

I use a white list to identify the types of PDFs to parse. Unfortunately, I've never encountered a Rebalance PDF, so I never wrote anything to parse them. If you feel comfortable doing so, would you mind emailing me (frank.c.fort@gmail.com) the file name of the PDF, and if you could, what would be especially helpful would be the entire PDF file itself, which I can then use to test my code. Totally understand if you don't feel comfortable doing so.

Thanks,
Frank
