### ISSUE TITLE
Version 0.1.1 fails to install

### ISSUE THREAD

**Issue by gkm4d** [fcfort/betterment-csv-chrome#45]
Attempting to install 0.1.1 results in the following:

![capture](https://cloud.githubusercontent.com/assets/3179912/20867859/a0a2801a-ba1b-11e6-8d68-c4d02011aa64.PNG)

I previously had no issues with 0.1.0.  I don't know anything about chrome extension packaging, but dist/builds/betterment-csv-chrome-0.1.1.zip is missing both icon128.png and icon38.png.  Whereas, dist/builds/betterment-csv-chrome-0.1.0.zip previously contained both files.

**Comment by fcfort** [comment]
Ack thanks, fixing now.

**Comment by fcfort** [comment]
New version published, should take a few minutes to propagate.

**Comment by gkm4d** [comment]
Working now.  Thanks!
